### PR TITLE
Fix $friends->getRawList()

### PR DESCRIPTION
**Pull request by destruc7i0n**
They seem to have removed the "list" array from the returned value and now it is just the array itself...

### CODE REVIEW

**Comment by Plancke** [comment]
I don't see the point of this one?

**Comment by Plancke** [comment]
```
{
success: true,
cache_time: 1461774806,
record: {
list: [],
uuid: "f025c1c7f55a4ea0b8d93f47d17dfe0f"
}
}
```

**Comment by destruc7i0n** [comment]
For me the current way doesn't work, only after I changed it worked and it still works to date.

**Comment by Plancke** [comment]
Yeah i forgot to push it to the non monog version, it's better this way in case we ever add more stuff to the friends api so we don't need to fix up tons of code

**Pull request closed without merging**
